general:
	python general_graphic.py $(d) $(s)

exhaustive:
	python exhaustive_prop.py $(d) $(s) $(f=4)

packet:
	python client_packet.py $(d) $(s)

dhcp:
	python client_dhcp.py $(d) $(s)

uav_removed:
	python uav_removed_energy.py $(d) $(s)
